// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b3779dd5-4f34-4480-bde2-d86863d1c1da",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1y1WcA1SS",
    "aws_user_pools_web_client_id": "rqbbmmfnf284qq13vkc40v49f"
};


export default awsmobile;
